### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by OneVoltTen** [speech-translator-ext/speech-translator-readme#13]
Hi!

Your OS: Windows 11
Web browser name and version: Chrome (latest) Version 120.0.6099.217 (Official Build) (64-bit)
The extension version: Latest
Your audio setup method: Additional information needed.
Selected Speech language, Google Translation Service English (AU), Translate To Language French.
Listening method: iFrame (START LISTENING button).
The issue description: Not working.
Steps to reproduce the issue: Am available on Discord - Username: OneVoltTen
Errors from the extension: No errors after enabling.
Errors from your browser Console Log on the page: No errors.

I'm also a developer so feel free to I'd be happy to help with a few of the issues I'v encountered if you'd like help.

**Comment by OneVoltTen** [comment]
Tested also not working in incognito with no other extensions enabled.

**Comment by OneVoltTen** [comment]
Tested also not working in MS Edge.

**Comment by OneVoltTen** [comment]
![2024-01-16 23_52_57-Sound](https://github.com/speech-translator-ext/speech-translator-readme/assets/11697505/607b87ff-7bbc-4378-9290-3771387cafb8)
Audio setup

**Comment by kappaflow** [comment]
Hi,
Please can you provide some more information, so I can assist you further.

1. Can you tell your audio setup method? (_Setup 1. Capture your system playback audio_ or _Setup 2. Capture audio from your microphone (any audio device)_)
2. Can you try to check that the selected audio input device has a correct audio playing while the extension is listening?
3. Can you try to listen in a popup window and tell what you have in the console log?
4. Have you tried to follow the [troubleshooting guide](https://github.com/speech-translator-ext/speech-translator-readme/blob/main/TROUBLESHOOTING.md)?

Thanks.

**Comment by kappaflow** [comment]
@OneVoltTen have you been able to fix the issue?

**Comment by kappaflow** [comment]
It looks like you have resolved the issue, but if not feel free to re-create it.

**Comment by OneVoltTen** [comment]
Hi @kappaflow sorry have been busy.

1. Audio capture is from the default audio device, disabled every other audio device then restarted the browser, no luck.
2. Every other audio device is disabled, restarted browser, disabled all other extensions, no luck.
3. Opened in incognito, same issue.
It's simpler if you could add me on discord onevoltten (available GMT+10 5pm-12pm), then I'll give you rdp access to my pc.

**Comment by kappaflow** [comment]
> Audio capture is from the default audio device, disabled every other audio device then restarted the browser, no luck.

Its not an audio method, it is an audio device. There are only 2 methods/setups you can find in the instruction: **Setup 1. Capture your system playback audio** and **Setup 2. and Capture audio from your microphone (any audio device)**
In case of Setup 1, please tell if you use **Virtual Cable** or **Stereo Mix**? Please keep in mind, in case of using Bluetooth audio device you might need to use **Stereo Mix** method to make it work.

> Every other audio device is disabled, restarted browser, disabled all other extensions, no luck.

Based on your screenshots your audio setup is wrong. Most likely you just need to read the audio instruction carefully to fix the issue.

> It's simpler if you could add me on discord onevoltten (available GMT+10 5pm-12pm), then I'll give you rdp access to my pc.

I am quite busy with other projects... not sure if can find time to do that in the next few days at least. So please try to follow the instruction again, it has all information you need to fix the issue.
