### ISSUE TITLE
Issues with long interviews.

### ISSUE THREAD

**Issue by blaues** [speech-translator-ext/speech-translator-readme#18]
I think it would be great if there was an option to change the direction of text scrolling. You know, like how most chat programs work! It would make reading individual sentences and the subtitle history flow smoothly, just like a cool "vertical crawl". Wouldn't that be awesome?

**Comment by kappaflow** [comment]
I have replied about that here #15 and I would recommend to discuss that feature request there.

But if you want to just read or work with the transcribed or/and translated text, I would recommend to use `4. Record transcribed and translated text` method from the instruction.
