### ISSUE TITLE
Extension won't add

### ISSUE THREAD

**Issue by teresazu** [speech-translator-ext/speech-translator-readme#20]
![chrome update done](https://github.com/speech-translator-ext/speech-translator-readme/assets/159500500/4149ef45-ae30-4e1a-b2a0-84a1f16faf8e)
extension will not load using Google Chrome latest version
Windows 10 64 bit OS

**Comment by kappaflow** [comment]
@teresazu can you tell me what happens when you click "Add extension" button?
