### ISSUE TITLE
errors in console

### ISSUE THREAD

**Issue by Kaisei2434** [speech-translator-ext/speech-translator-readme#25]
Hi, I seem to have a problem where for the first few hours of installing the extension, it works great on both Chrome and Edge. But after my PC goes into standby modus or restarting my PC, it'll suddenly stop working. Reinstalling the extension seems to fix the problem, but then the cycle repeats itself when it ultimately stops working again. The same thing happens on Edge, both on its browser and as a standalone app. I added a screenshot of the console, which seems to contain some errors but I have no clue what they mean sorry.
![image](https://github.com/speech-translator-ext/speech-translator-readme/assets/167020356/130cb70d-cbfa-49a0-b9e8-ee083e6ddb82)

Also, no clue if it matters but I have adblock and ublock on chrome.

Your OS - Windows 11 Home, ver. 23H2 build 22631.3447
Web browser name and version - Google Chrome ver, 123.0.6312.123
The extension version - ver. 0.2.2
Your audio setup method - Setup method 2 using VB Cable, I'm using headphones which are plugged to my mic
Selected Speech language, Translation Service, Translate To Language - Japanese to English using Google Translate public
Listening method: iFrame (START LISTENING button), Popup, Side Panel. For iFrame method please specify the website where you are starting listening - iFrame on Youtube
The issue description - See the above
Steps to reproduce the issue - When installing the extension I've followed the instructions 100% which is why is works fine at the start. After it stopped working for the first time I checked all related settings but couldn't find anything that might have somehow changed in the meantime. When deleting the extension I deleted VB Cable as well by chucking the entire folder away.
Errors from the extension (if you have any): chrome://extensions/?errors=jodfjmaiakpnmeddgpeflpafebmlhppn (you might need to enable Collect errors first here: chrome://extensions/?id=jodfjmaiakpnmeddgpeflpafebmlhppn )
Errors from your browser Console Log on the page where you experience the issue (if you have any)

**Comment by kappaflow** [comment]
@Kaisei2434 the errors in the console log are not related to the extension...
Can you confirm that you've tried to restart the web browser after getting back from the stand by mode?

Based on your description the problem may be related not to the extension itself, but your audio setup in the system. While you are experiencing the issue, can you check the audio device settings and make sure you have audio on the device that is selected in your web browser (which capture the audio for the translation)? Basically, its article 3 from the [troubleshooting guide](https://github.com/speech-translator-ext/speech-translator-readme/blob/main/TROUBLESHOOTING.md).

**Comment by Kaisei2434** [comment]
Hi, I can confirm I've been restaring the web browser as well. As for audio device settings, I'm not entirely sure what you mean, so I added screenshots of anything audio related in my system:
![image](https://github.com/speech-translator-ext/speech-translator-readme/assets/167020356/ddf23c69-abef-4b9b-b3a0-e482d403a6d0)
![image](https://github.com/speech-translator-ext/speech-translator-readme/assets/167020356/ee4d6ce4-e2f6-4a97-98de-602250cdfc29)
![image](https://github.com/speech-translator-ext/speech-translator-readme/assets/167020356/43c2462c-c9f9-4492-b2f6-69e4cfe788be)
![image](https://github.com/speech-translator-ext/speech-translator-readme/assets/167020356/9f398622-4562-4bea-b31e-b0b880533ff0)
![image](https://github.com/speech-translator-ext/speech-translator-readme/assets/167020356/4141bf93-0783-4a5b-a5a8-6bbb98efcc86)
![image](https://github.com/speech-translator-ext/speech-translator-readme/assets/167020356/5d1f9582-79da-459a-99fc-c566e3b3336c)

**Comment by kappaflow** [comment]
Please make sure, when you click **Grant Audio Permission** in the extension you set there VB Cable as an input device.
Also, try to play any video (with an audio part), and make sure ![on this menu](https://github.com/speech-translator-ext/speech-translator-readme/assets/68439996/5fe76139-ec22-4c75-9208-3f14327e0de2) indication of an audio level near "Cable output" (the green bars).

Also based on this screenshot the input audio device for Chrome is "Default", which is Yeti mic in your case.
![image](https://github.com/speech-translator-ext/speech-translator-readme/assets/68439996/3815193f-d36d-48fb-a4ef-a91e585f5e74)

Also here, I can see that you have Yeti mic selected as an input device, instead of VB Cable, it means it captures audio from your mic instead of the video you play.
![image](https://github.com/speech-translator-ext/speech-translator-readme/assets/68439996/93b8d65a-38d2-44ed-bcbb-bc9e0ce3cb0d)

**Comment by Kaisei2434** [comment]
Hi, I changed the default for Google Chrome in my volume mixer settings to VB Cable and changed the input device on Chrome for audio permission to VB Cable as well. Everything seems to be working now, thank you very much!
