### ISSUE TITLE
Didn't work on a virtual Soundcard (Dante)

### ISSUE THREAD

**Issue by ralf-schmid** [speech-translator-ext/speech-translator-readme#26]
Hi, 
I would like to use your wonderful Chrome extention on a MacBook. When I choose the internal microphone it works pretty well, but when I switch to a virtual soundcard from Dante (https://www.getdante.com/de/software-grundlagen/dante-virtual-soundcard/) there is no output. In system prefercences I can see that there is sound input from the virtual soundcard. Is there anything I could check or do to fix it?
Is there a possibility to get a logfile with maybe more details?
Thanks in advance!
Regards,
Ralf

**Comment by kappaflow** [comment]
@ralf-schmid hi,
Do you choose a different input device in the browser when switch to a virtual soundcard?
Have you tried to use any other websites that uses microphone input such as https://www.google.com/intl/en/chrome/demos/speech.html with a virtual soundcard?
Does virtual soundcard from Dante works through ASIO?

**Comment by ralf-schmid** [comment]
Thank you, my fault (a typical PEBCAK). With your hint I could fix my problem. Thank you for the great plugin! It fits exactly to my need and works great!
