### ISSUE TITLE
There's a sound problem

### ISSUE THREAD

**Issue by Archeta1** [speech-translator-ext/speech-translator-readme#30]
I was listening to the sound through my earphones
It's not recognized by the translator program
I need to use Realtek HD Audio 2nd output to hear the sound and 
use CABLE to use the program. So I can't hear the sound. I'll attach a picture

I followed everything I was told to set up, and I checked it several times
However, the sound was not recognized, so I installed a virtual audio cable

It was recognized in the program, but I couldn't hear anything

Please tell me how to use the program while listening to the sound

I installed voicemaster, but I don't know how to use it, and the problem was not solved

Do I need to use the audio interface to solve this problem or is there a way to solve it by installing the program?
Or maybe using a speaker can solve it?

I hope you have a good answer. Thank you

![화면 캡처 2024-08-09 172044](https://github.com/user-attachments/assets/5b8d0b57-82cb-49e9-815d-76691c60cebc)

**Comment by kappaflow** [comment]
Do you use Bluetooth/USB headphones or wired (with a typical minijack connected to you PC)?
Have you tried to follow the troubleshooting guide?
https://github.com/speech-translator-ext/speech-translator-readme/blob/main/TROUBLESHOOTING.md

Anyway, it should work with the Virtual Audio Cable setup, without installing the voicemeter mixer.
Your description is a bit unclear, so its a little bit difficult to troubleshoot. It looks like you selected the wrong audio device somewhere or didn't set the checkmark near "Listen to this device" in the last step.

Please try to follow "Windows (Virtual Audio Cable)" setup once again. Make sure you followed the step 5 with setting the default device. Also, please make sure you followed the step 8, where you must set the checkmark and select your headphones device in the dropdown list.

Then, please make sure, your web browser uses VB-Cable audio device to capture your audio. You can do it on this page:
`chrome://settings/content/microphone`

**Comment by Archeta1** [comment]
Wow, it worked out. Thank you so much
Step eight of the setup was the problem
I'm sorry to bother you. I'll use the program well Thank you for making a good program
