### ISSUE TITLE
it instantly closes wen i hit start listening on Chrome

### ISSUE THREAD

**Issue by ggd001** [speech-translator-ext/speech-translator-readme#34]
![Screenshot 2024-09-02 083018](https://github.com/user-attachments/assets/879cd121-f8e7-493d-bfa5-ba3f436fec74)
![image](https://github.com/user-attachments/assets/5e292568-f5ac-4da7-9232-c4a03d2952ca)
as far as i now i have configured evirating as te instructions sad but it das not work please help

**Comment by kappaflow** [comment]
Thank you for the screenshots. It seems like you are using Windows 11... Please try to set **Stereo Mix** device as Default Input Device, like on this screenshot (ignore that it is Cable Input there). Also, you can set the Input device on the **Sound** window (your second screenshot) as well.

![image](https://github.com/user-attachments/assets/09c06816-c423-467d-bcac-79b89af060c5)

Please let me know if it helps

**Comment by ggd001** [comment]
I dit that and it das not work. But i dit find the issue. Apparently I still needed to grand sound recorder access to my microphone. Which is weird because it has worked before without me needing to set that option.

**Comment by kappaflow** [comment]
Thanks for the update! I am glad it works. I had some weird issues with the audio device selection / permission in Chrome on Windows 11 as well...

**Comment by kappaflow** [comment]
Again, thank you for the feedback. I am closing the ticket for now. Also, it would be great if you could edit the feedback in the chrome store by adding your solution for the problem.
